from enum import Enum


class PROBE_TASK_TYPES(Enum):
    SENTENCE = "SENTENCE"
    SENTENCE_TOKENS = "SENTENCE_TOKENS"
    TOPIC_SENTENCE = "TOPIC_SENTENCE"
    TOPIC_SENTENCE_TOKENS = "TOPIC_SENTENCE_TOKENS"